name: Main Branch Screenshots

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies using pnpm
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build
        run: npm run build:ci

      - name: Screenshots
        run: npx playwright test
        continue-on-error: true
        id: screenshots

      - name: WebshotArchive Action
        uses: webshotarchive/github-action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          screenshotsFolder: dist/playwright
          clientId: ${{ secrets.WSA_CLIENT_ID }}
          clientSecret: ${{ secrets.WSA_CLIENT_SECRET }}
          projectId: ${{secrets.WSA_PROJECT_ID}}

      - name: Check if screenshots failed
        if: steps.screenshots.outcome == 'failure'
        run: exit 1
