name: Pull Request Screenshots

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies using npm
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build
        run: npm run build:ci

      - name: Screenshots
        run: npx playwright test
        continue-on-error: true
        id: screenshots

      - name: WebshotArchive Action
        if: github.actor != 'dependabot[bot]'
        uses: webshotarchive/github-action@latest
        with:
          screenshotsFolder: dist/playwright
          clientId: ${{ secrets.WSA_CLIENT_ID }}
          clientSecret: ${{ secrets.WSA_CLIENT_SECRET }}
          projectId: 68d0035806762c8b1918d6bf

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-screenshots
          path: ./dist/playwright/
          retention-days: 30

      - name: Upload HTML report to Azure
        shell: bash
        if: steps.screenshots.outcome == 'failure'
        run: |
          REPORT_DIR='run-${{ github.run_id }}-${{ github.run_attempt }}'
          azcopy cp --recursive "./playwright-report/*" "https://webshotarchiveplaywright.blob.core.windows.net/\$web/$REPORT_DIR"
          echo "::notice title=HTML report url::https://webshotarchiveplaywright.z13.web.core.windows.net/$REPORT_DIR/index.html"
        env:
          AZCOPY_AUTO_LOGIN_TYPE: SPN
          AZCOPY_SPA_APPLICATION_ID: '${{ secrets.AZCOPY_SPA_APPLICATION_ID }}'
          AZCOPY_SPA_CLIENT_SECRET: '${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}'
          AZCOPY_TENANT_ID: '${{ secrets.AZCOPY_TENANT_ID }}'

      - name: Check if screenshots failed
        if: steps.screenshots.outcome == 'failure'
        run: exit 1
